network:
  version: 2
  renderer: NetworkManager
  ethernets:
    # Set Static IP 192.168.0.12, and disabled DHCP for ipv4 and ipv6.
    # https://blog.oddbit.com/post/2018-03-12-using-docker-macvlan-networks/
    enp1s0:
      dhcp4: no
      addresses:
        - 192.168.0.12/24
      gateway4: 192.168.0.1
      nameservers:
        addresses: [127.0.0.1, 1.1.1.1]
      dhcp6: no
  bridges:
    mynet-shim:
      interfaces: [enp1s0]
      addresses: [192.168.1.127/32]
      routes:
        - to: 192.168.1.96/27
          via: 192.168.1.127
  vlans:
    mynet-shim-macvlan:
      link: macvlan-shim
      macvlan:
        mode: bridge