homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://10.10.10.98
serial:
  port: /dev/ttyACM0
frontend:
  port: 8080
  url: 'https://ctrlcenter.gq'
advanced:
  network_key:
    - 56
    - 214
    - 134
    - 220
    - 196
    - 159
    - 75
    - 231
    - 53
    - 231
    - 247
    - 208
    - 19
    - 193
    - 195
    - 97
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0x00158d00097636d6':
    friendly_name: '0x00158d00097636d6'