version: "3.9"
services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      # Automatic upgrade to HTTPS for HTTP connections
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"

      - "--certificatesresolvers.cfresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.cfresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cfresolver.acme.email=xhyq@proton.me"
      - "--certificatesresolvers.cfresolver.acme.storage=/letsencrypt/acme.json"

      # Cloudflare - Potential Race Condition - Disable Prop Check
      - "--certificatesResolvers.cfresolver.acme.dnsChallenge.delayBeforeCheck=60"
      - "--certificatesresolvers.cfresolver.acme.dnschallenge.disablepropagationcheck=true"

      # Wildcard certificate generation
      - --entrypoints.websecure.http.tls.domains[0].main=rhombo.xyz
      - --entrypoints.websecure.http.tls.domains[0].sans=*.rhombo.xyz

      # Testing / Setup - Use staging endpoint
      # - "--certificatesresolvers.cfresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    env_file:
      - ./.env
    volumes:
      - "/opt/appdata/traefik_config/:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefiknet

  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.rhombo.xyz`)"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=cfresolver"
    restart: unless-stopped
    networks:
      - traefiknet

  librespeed:
    image: ghcr.io/linuxserver/librespeed
    container_name: librespeed
    restart: unless-stopped
    # ports:
    #   - 80:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librespeed.rule=Host(`libre.rhombo.xyz`)"
      - "traefik.http.services.librespeed.loadbalancer.server.port=80"
      - "traefik.http.routers.librespeed.entrypoints=websecure"
      - "traefik.http.routers.librespeed.tls.certresolver=cfresolver"
    networks:
      - traefiknet

networks:
  traefiknet:
    external: true