- id: '1599632613312'
  name: General Lights
  entities:
    light.hue_color_lamp_1:
      brightness: 255
      color_temp: 400
      effect: none
      effect_list:
      - colorloop
      - random
      friendly_name: Light_Office-Desk
      max_mireds: 500
      min_mireds: 153
      state: 'on'
      supported_features: 63
    switch.lithium_i:
      friendly_name: Light_Living-Room
      state: 'off'
    switch.lithium_iii:
      friendly_name: Light_Office-Corner
      state: 'off'
